#!/usr/bin/env python
#
# ROM BUILD SCRIPT - By franco28.
#
# Do not edit this file unless you know what you are doing

from __future__ import print_function
import sys, os

def getChar():
	import tty, sys, termios
	
	def _ttyRead():
		fd = sys.stdin.fileno()
		oldSettings = termios.tcgetattr(fd)
		try:
			tty.setraw(fd)
			choice = sys.stdin.read(1)
		finally:
			termios.tcsetattr(fd, termios.TCSADRAIN, oldSettings)
		return choice

	return _ttyRead().lower()

makerom = 'makerom'+os.sep+'source'+os.sep+'makerom'

print('Loading ...')
os.system(makerom)
answer = ''
while answer != 'q':
	print('\n\n\033[0m\033[32mPress "q" to Quit, or "r" to Restart\033[0m')
	answer = getChar()
	if answer == 'r':
		print(' ')
		print('Loading ...')
		print(' ')
		os.system(makerom)

sys.exit()
